---
title: " "
---



# Debugging avanzado

En esta sección, se enumeran algunos problemas comunes que puede encontrar y algunas técnicas para resolverlos dentro de su modelo.

## Si los residuos tienen patrones sustanciales

A menudo es difícil identificar la causa de los residuos que tienen patrones sustanciales, pero dos posibles razones por las que esto podría suceder son valores iniciales poco realistas o una especificación de modelo deficiente. Si tiene residuos con un patrón sustancial, puede intentar cambiar los valores iniciales. Si un parámetro no se mueve del valor inicial, es posible que no haya suficiente información para determinar su valor y que sea necesario fijar el valor en el modelo. Si el parámetro se mueve con diferentes valores iniciales, es posible que el valor inicial utilizado antes no fuera razonable y, por lo tanto, cambiar el valor inicial a un valor razonable soluciona el problema.

## Si SS3 se ejecuta, pero hay un gradiente final muy grande

Los gradientes grandes generalmente se informan en el archivo de **warnings.sso**, por lo que este problema debería estar claro al examinar el archivo después de ejecutar un modelo. Si este es el caso, intente lo siguiente:

* Examine **Report.sso** en busca de parámetros que estén dentro o cerca de los límites, ya que estos pueden ser los parámetros que están causando problemas. Depende del valor, pero puede considerar cambiar sus límites o los parámetros, según lo que parezca más plausible dado su modelo.
* Examine los residuos para identificar si hay una  falta de ajuste general. Esto puede indicar que el algoritmo ADMB no pudo encontrar el mínimo global. Pruebe valores iniciales alternativos para intentar resolver este problema. Sin embargo, también es posible que haya un gran conflicto entre la estructura de su modelo y el archivo de su modelo, en cuyo caso es posible que desee reconsiderar la especificación del modelo; tal vez haya una estructura de modelo alternativa que tenga más sentido para la población.


## Si la Hessiana no se invierte

La información de la Hessiana se informa en el archivo **Report.sso**, así que vaya a esta sección para confirmar si se trata de un problema. Este es un problema difícil de resolver, pero puede ser necesario considerar modelos alternativos si la hessiana no se invierte.

# Algunas preguntas a considerar durante el desarrollo del modelo

Hay muchos elementos a considerar en un modelo SS3. A continuación se presentan algunas preguntas y consideraciones que los usuarios experimentados de SS3 han utilizado para comprobar que su modelo tiene sentido durante todo el proceso de desarrollo iterativo del modelo.

## ¿Mi modelo tiene sentido?

* ¿Tiene sentido la biología? ¿Selectividad?
* ¿El modelo se ajusta a los índices? ¿Datos de longitud y edad?
* ¿Cuál es el patrón en el reclutamiento?
* ¿Las priors coinciden con lo que pensé que estaba especificando?

## ¿Mi modelo ajusta bien?

La función `r4ss::SS_output()` imprime algunos diagnósticos muy útiles en la ventana de la consola R, incluida una lista de los parámetros estimados, el valor estimado, si el parámetro está alcanzando un límite, el gradiente y el tipo anterior. Utilice este (u otros archivos de salida SS3) para responder:

* ¿Se movió el parámetro del valor inicial?
* ¿Está el parámetro llegando a un límite?
* ¿El gradiente del parámetro es bajo?

Debajo de las estimaciones de parámetros que r4ss::SS_output() imprime en la consola, hay una sección específica que resalta los parámetros con los gradientes de modelo más altos. Examinar esta lista podría indicar qué parámetros (si los hay) pueden necesitar ser corregidos debido a la falta de información en los datos.

Por ejemplo, puede haber parámetros de selectividad incluidos en la lista donde pequeños cambios en el valor del parámetro no cambian los resultados del modelo (o la forma de la selectividad).

## ¿Mi ponderación de datos tiene sentido?

La función `r4ss::SS_output()` imprime información sobre la sintonización de la consola R. Esto incluye información de ajuste para datos de longitud y edad que se pueden usar para la ponderación de datos cuando se usa la ponderación de McAllister Ianelli (es decir, ponderación por la media armónica).

La función `r4ss::SS_plots()` crea cifras medias de longitud y edad con leyendas que muestran los pesos de Francis recomendados para cada fuente de datos. Incluso si está utilizando un enfoque de ponderación de datos alternativo (es decir, Francis, Dirichlet u otro), siempre es una buena práctica explorar un enfoque alternativo y ver cómo la ponderación de datos cambia el modelo.

## ¿Ajusté correctamente la variación del reclutamiento?

Verifique la información de sigmaR (es decir, desviación estándar de desarrollo de reclutamiento). El parámetro sigmaR generalmente se fija dentro del modelo, por lo que si no se fija dentro de su modelo, debe considerar si tiene o no sentido para la población y dada la calidad y cantidad de datos.

Para un valor fijo de sigmaR, una sección del resultado proporcionará diagnósticos para determinar si el valor fijo de sigmaR está capturando las variaciones estimadas en el reclutamiento. La función `r4ss::SS_output()` imprimirá un valor recomendado basado en la variación en las desviaciones de reclutamiento estimadas que quizás desee considerar usar.

